"""Golden-master characterization tests for the stellar-jax refactor epic (#476).

PURPOSE: These tests pin the EXACT numerical output of the current code at fixed
configs. They are NOT physics validation tests (those live in tests/test_*.py per module). They
are REFACTOR GUARDS: if any of these change, the refactor introduced a behavioral
change — which must be investigated (either the refactor has a bug, or the test
needs re-baselining with justification).

DESIGN (docs/design/refactor-epic-report.md §3.1):
- All tests use fixed_dt to eliminate adaptive-dt nondeterminism.
- Exact f64 match (atol=0, rtol=0) for composition ops (pure array ops, deterministic).
- evolve_star + gradient + eigenfreq outputs go through XLA compilation, whose
  float-operation ORDER shifts across refactors / JAX versions, drifting results by
  ~1e-7 (physically negligible — physics is validated at <0.10 dex, i.e. ~20%). A
  bit-level pin (rtol=1e-12) therefore flagged benign reorders as "behavior changes"
  and forced a manual re-baseline on every refactor. These are now pinned at
  atol=1e-8, rtol=1e-5 (still 4-5 orders tighter than physics validation, so a REAL
  regression — which is percent-level — is still caught, while benign float
  reordering is tolerated). eigenfreq uses rtol=1e-9.
  Incident (2026-08-13): the #469 diffusion_factor knob (a default-1.0 differentiable
  input) drifted the M=1.0 log_L golden by 2.8e-7, which the old 1e-12 pin failed —
  after the validate.py>1MiB CI-discovery bug had kept this test from running on the
  intervening refactor merges. See project.md steering.

REFERENCE VALUES: Generated by `scripts/generate_golden_master.py` and committed
as `tests/golden_master_ref.npz`. The generation script records the exact output
of the current code (main HEAD at the time of creation). Re-baselining requires
running the script again and committing the updated .npz.

MARKS + CI ROUTING (updated 2026-09-10, #1113 in-house rework):
- @pytest.mark.fast: composition ops + oscillation + mlt_nabla/cell_residual value pins
  + AD-vs-FD + STRUCTURAL pytree asserts (no evolve_star, <10s each). These run PER-WAVE.
  They are the actual refactor guards: value pins catch a changed number, structural asserts
  catch the silent-zero-gradient bug (an arg wrongly made static/nondiff after bundling).
- @pytest.mark.suspended: the HEAVY value+gradient goldens (forward evolve, ∂logL/∂M,
  ∂logTe/∂α, seismic ∂σ²/∂M, the custom_vjp cotangent pins, one-step evolve, evolve_solar).
  Each compiles a full forward/backward pass (~10-40 min, up to the 120 GB CI tier). They are
  the refactor TRANSITION oracle — run ON-DEMAND during the #785 batches (locally or via a
  standalone run), and NIGHTLY — NOT on every per-wave CI (a permanent heavy per-wave cost for
  a transition-only net is the wrong trade; this is the fix that superseded PR#1120). The
  golden VALUES are committed in golden_master_ref.npz and stay valid; re-enabling per-wave is
  a one-line mark flip if ever wanted.

REFACTOR DISCIPLINE (the three rules that keep a bit-identity refactor honest):
1. If you have to LOOSEN a tolerance or EDIT a golden/gate to make it pass, that is NOT a
   refactor — STOP. A bit-identity refactor changes no number; a moved number is a bug (or a
   deliberate, separately-justified behavioral change that must be documented + re-baselined).
2. COMMIT PER FUNCTION. Each bundled/split function is its own commit so a golden/gradient
   regression bisects to ONE function, not a blended diff.
3. Golden churn is a REVIEWER RED FLAG. Re-baselining requires re-running
   scripts/generate_golden_master.py with a commit message that says WHAT changed and WHY.
   An unexplained .npz change in a "pure refactor" PR means the refactor moved behavior.

HELPER FOR THE BATCHES: assert_differentiable_leaves(...) (below, §0) — the per-function
structural guard the #1114/#1115/#1116 batches call after bundling a function's args into a
frozen pytree config, to prove each differentiated param is still a live pytree LEAF (not
static). Near-free (@fast, no compile) so it scales to all 169 refactored functions.
"""

import os
import sys
import gzip

import numpy as np
import pytest

# Ensure the project root is importable
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import jax
import jax.numpy as jnp

jax.config.update('jax_enable_x64', True)

# ===========================================================================
# Reference file path
# ===========================================================================
_REF_DIR = os.path.dirname(os.path.abspath(__file__))
_REF_FILE = os.path.join(_REF_DIR, "golden_master_ref.npz")


def _load_ref():
    """Load the golden-master reference .npz file."""
    if not os.path.isfile(_REF_FILE):
        pytest.skip(
            f"Golden-master reference not found at {_REF_FILE}. "
            "Run `python scripts/generate_golden_master.py` to create it."
        )
    return np.load(_REF_FILE, allow_pickle=True)


# ===========================================================================
# §0. REUSABLE STRUCTURAL HELPER FOR THE REFACTOR BATCHES (//)
# ===========================================================================
# The per-function structural guard against the silent-zero-gradient bug.
#
# THE BUG IT CATCHES: when a refactor bundles a function's loose args into a
# frozen pytree config (register_dataclass with data_fields vs meta_fields, or a
# NamedTuple/dataclass), it is easy to put a DIFFERENTIATED array into a
# meta_field (static) by mistake. The function still runs and returns the right
# VALUE, but jax.grad through it is now silently ZERO for that param — a forward
# value-golden will NOT catch it. A pytree-leaf assertion does: a differentiated
# param MUST flatten to a leaf; a static param does not.
#
# HOW THE BATCHES USE IT: after bundling fn's args into `config`, call
#   assert_differentiable_leaves(config, ["alpha_mlt", "Z", "M_star", ...])
# listing every field that USED to be a differentiated argument. If any is now
# static (not a leaf), this raises — before the bad gradient reaches production.
#
# WHY IT SCALES: pure pytree flatten, no compile, milliseconds — so the batches
# can call it once PER refactored function (all 169), unlike the heavy value/grad
# goldens which only cover ~5 representatives.
# ===========================================================================


def assert_differentiable_leaves(config, expected_leaf_params, *, allow_missing=False):
    """Assert each named differentiated param is a LEAF (not static) in `config`.

    Args:
        config: the frozen-pytree config object produced by a bundling refactor
            (a registered dataclass / NamedTuple / any registered pytree).
        expected_leaf_params: iterable of attribute names that were differentiated
            arguments before the refactor and MUST remain pytree leaves after it.
        allow_missing: if True, a name that is not an attribute of `config` is
            skipped (default False → a missing name is an error, since it usually
            means the field was renamed or dropped by the refactor).

    Raises:
        AssertionError: if any expected param is absent (unless allow_missing) or
            is not a leaf of the flattened pytree (i.e. was made static/meta).

    This is the structural half of the refactor net (the value/grad goldens are
    the numerical half). It has no JAX compile cost.
    """
    import jax.tree_util as jtu

    # Identity of each leaf, so we can test membership without relying on == of
    # arrays (which is ambiguous). Leaves are the differentiable payload; anything
    # in a meta_field/static slot is NOT in this list.
    leaves = jtu.tree_leaves(config)
    leaf_ids = {id(x) for x in leaves}

    missing = []
    static = []
    for name in expected_leaf_params:
        if not hasattr(config, name):
            if allow_missing:
                continue
            missing.append(name)
            continue
        val = getattr(config, name)
        if id(val) not in leaf_ids:
            static.append(name)

    problems = []
    if missing:
        problems.append(
            f"missing from config (renamed/dropped by refactor?): {missing}")
    if static:
        problems.append(
            f"present but NOT a pytree leaf — made static/meta by the refactor, "
            f"so jax.grad w.r.t. it is now SILENTLY ZERO: {static}")
    assert not problems, (
        f"assert_differentiable_leaves failed for {type(config).__name__}: "
        + "; ".join(problems)
        + f".\nFlattened leaves count={len(leaves)}. Every differentiated arg "
        "must remain a data_field/leaf, never a meta_field/static.")


# ===========================================================================
# §1. COMPOSITION OPERATOR PINS (fast, no evolve_star)
# ===========================================================================
# These test burn_cno, mix_composition, and diffuse_composition on FIXED
# synthetic inputs. They run in <5s (no JIT compilation of the full solver).
# Tolerance: exact f64 match (atol=0) — these are pure array operations with
# no stochastic element.
# ===========================================================================


def _make_synthetic_shell_data():
    """Create a fixed synthetic shell_data array for composition tests.

    Shell_data layout (from henyey.py:2753 extract_shell_data_from_henyey):
      col 0: eps (nuclear energy generation rate, erg/g/s)
      col 1: q (mass fraction coordinate, m/M_star)
      col 2: nabla_rad (radiative temperature gradient)
      col 3: nabla_ad (adiabatic temperature gradient)
      col 4: Hp/R (pressure scale height / stellar radius)
      col 5: dm/dr normalized (= dm_dr * R_star / M_star)
      col 6: log10(T)  [K]
      col 7: log10(rho) [g/cm³]
      col 8: nabla (actual temperature gradient, including MLT)
      col 9: log10(P) [dyne/cm²]

    The array is in SURFACE-TO-CENTER order (index 0 = surface, index -1 = center),
    matching extract_shell_data_from_henyey which returns shell_data[::-1] (i.e.
    reverses the center-to-surface Henyey mesh to surface-to-center).

    We create a physically-reasonable 200-zone solar interior profile.
    burn_cno and diffuse_composition read cols 6,7 as logT/logrho; mix_composition
    reads cols 1-5. Getting this layout right is critical — a wrong column mapping
    produces NaN in diffusion (logT interpreted as raw density → T=10^150).
    """
    from stellar_jax.config.mesh_defaults import N_COMP, COMP_MFRACS

    n = N_COMP  # 200 zones

    # Mass fraction: use COMP_MFRACS (center-to-surface, q^3 spacing)
    # The Henyey mesh is surface-to-center after the [::-1] reversal in
    # extract_shell_data_from_henyey, but COMP_MFRACS goes 0→1 (center→surface).
    # The composition ops sort/interp using mf_shells anyway, so the ordering
    # within shell_data doesn't matter as long as mf is monotonic somewhere.
    mf = np.array(COMP_MFRACS)  # 0 (center) → 1 (surface)

    # col 0: eps_nuc (nuclear energy generation, erg/g/s)
    # ~10 erg/g/s at center (PP chain), ~0 at surface
    eps_nuc = 10.0 * np.exp(-mf / 0.05)  # concentrated in core

    # col 2,3: nabla_rad and nabla_ad
    nabla_ad = np.full(n, 0.4)  # ideal-gas nad
    # Convective core (nabla_rad > nabla_ad) for inner ~10% by mass
    nabla_rad = np.where(mf < 0.10, 0.8, 0.25)

    # col 4: Hp/R (pressure scale height / radius)
    hp_over_R = 0.1 * (1.0 - mf) + 0.01

    # col 5: dm/dr normalized
    dm_dr_norm = np.ones(n) * 3.0

    # col 6: log10(T) — core ~1.5e7 K (logT=7.17), surface ~6000 K (logT=3.78)
    logT = np.linspace(7.17, 3.78, n)

    # col 7: log10(rho) — core ~150 g/cm³ (logrho=2.18), surface ~1e-7 (logrho=-7)
    logrho = np.linspace(2.18, -7.0, n)

    # col 8: nabla (actual temperature gradient — equals nabla_ad in CZ, nabla_rad outside)
    nabla = np.where(mf < 0.10, nabla_ad, nabla_rad)

    # col 9: log10(P) — core ~2e17 (logP=17.3), surface ~1e5 (logP=5.0)
    logP = np.linspace(17.3, 5.0, n)

    shell_data = np.column_stack([eps_nuc, mf, nabla_rad, nabla_ad, hp_over_R,
                                  dm_dr_norm, logT, logrho, nabla, logP])
    return shell_data.astype(np.float64)


@pytest.mark.fast
def test_golden_burn_cno():
    """Pin burn_cno output on fixed synthetic inputs.

    Quantity pinned: (C12_out, C13_out, N14_out) arrays (N_COMP=200 each).
    Config: dt=2e6 yr (in seconds), uniform initial CNO from Z=0.014.
    Tolerance: exact f64 match (deterministic pure-JAX computation).
    """
    import stellar_jax.evolution as evolution
    from stellar_jax.config.constants import SECONDS_PER_YEAR
    from stellar_jax.config.mesh_defaults import N_COMP, COMP_MFRACS

    ref = _load_ref()

    # Fixed inputs
    Z = 0.014
    X = np.full(N_COMP, 0.7)  # uniform hydrogen
    C12_init = np.full(N_COMP, 0.142 * Z)  # solar C12/Z ratio
    C13_init = np.full(N_COMP, 0.0036 * Z)  # solar C13/Z ratio
    N14_init = np.full(N_COMP, 0.049 * Z)  # solar N14/Z ratio
    shell_data = _make_synthetic_shell_data()
    dt = 2e6 * SECONDS_PER_YEAR  # 2 Myr in seconds

    # Run
    C12_out, C13_out, N14_out = evolution.burn_cno(
        jnp.array(C12_init), jnp.array(C13_init), jnp.array(N14_init),
        jnp.array(X), jnp.array(shell_data), jnp.float64(dt)
    )

    # Pin
    np.testing.assert_allclose(
        np.array(C12_out), ref['burn_cno_C12'], atol=0, rtol=0,
        err_msg="burn_cno C12 output changed — refactor broke behavior"
    )
    np.testing.assert_allclose(
        np.array(C13_out), ref['burn_cno_C13'], atol=0, rtol=0,
        err_msg="burn_cno C13 output changed — refactor broke behavior"
    )
    np.testing.assert_allclose(
        np.array(N14_out), ref['burn_cno_N14'], atol=0, rtol=0,
        err_msg="burn_cno N14 output changed — refactor broke behavior"
    )


@pytest.mark.fast
def test_golden_mix_composition():
    """Pin mix_composition output on fixed synthetic inputs.

    Quantity pinned: X_mixed array (N_COMP=200).
    Config: M=1.0 M_sun, f_ov=0.016, synthetic shell_data with a convective core.
    Tolerance: exact f64 match.
    """
    import stellar_jax.evolution as evolution
    from stellar_jax.config.mesh_defaults import N_COMP

    ref = _load_ref()

    # Fixed inputs: a composition profile with a gradient (partially burned core)
    X = np.linspace(0.35, 0.70, N_COMP)  # burned core → pristine envelope
    shell_data = _make_synthetic_shell_data()

    X_mixed = evolution.mix_composition(
        jnp.array(X), jnp.array(shell_data), M_solar=1.0, f_ov=0.016
    )

    np.testing.assert_allclose(
        np.array(X_mixed), ref['mix_X'], atol=0, rtol=0,
        err_msg="mix_composition output changed — refactor broke behavior"
    )


@pytest.mark.fast
def test_golden_diffuse_composition():
    """Pin diffuse_composition output on fixed synthetic inputs.

    Quantity pinned: (X_out, Y_out) arrays (N_COMP=200 each).
    Config: dt=2e6 yr, M=1.0, uniform initial X/Y, synthetic shell_data.
    Tolerance: exact f64 match.
    """
    import stellar_jax.evolution as evolution
    from stellar_jax.config.constants import SECONDS_PER_YEAR
    from stellar_jax.config.mesh_defaults import N_COMP

    ref = _load_ref()

    # Fixed inputs
    X = np.full(N_COMP, 0.70)
    Y = np.full(N_COMP, 0.28)
    shell_data = _make_synthetic_shell_data()
    dt = 2e6 * SECONDS_PER_YEAR

    result = evolution.diffuse_composition(
        jnp.array(X), jnp.array(Y), jnp.array(shell_data),
        jnp.float64(dt), M_solar=1.0
    )

    # diffuse_composition returns (X_new, Y_new) or just X_new depending on version
    if isinstance(result, tuple):
        X_out, Y_out = result[0], result[1]
    else:
        X_out = result
        Y_out = None

    np.testing.assert_allclose(
        np.array(X_out), ref['diffuse_X'], atol=0, rtol=0,
        err_msg="diffuse_composition X output changed — refactor broke behavior"
    )
    if Y_out is not None and 'diffuse_Y' in ref:
        np.testing.assert_allclose(
            np.array(Y_out), ref['diffuse_Y'], atol=0, rtol=0,
            err_msg="diffuse_composition Y output changed — refactor broke behavior"
        )


# ===========================================================================
# §2. OSCILLATION PIN (fast, no evolve_star)
# ===========================================================================
# Test compute_eigenfreq_differentiable on a FIXED FGONG from the committed
# MESA comparison profiles. Runs in ~5-10s (one eigenvalue solve, no lax.scan).
# ===========================================================================


@pytest.mark.fast
def test_golden_eigenfreq_from_fgong():
    """Pin σ²(l=0) from a fixed FGONG file.

    Quantity pinned: sigma2 (dimensionless eigenfrequency squared) for the
    lowest l=0 mode in the [2500, 3500] μHz bracket.
    Source: data/mesa_comparison/profiles/1.0Msun/midMS.FGONG.gz
    Tolerance: exact f64 match (deterministic Brent root + RK4 integration).
    """
    import stellar_jax.oscillations as oscillations
    import stellar_jax.oscillations as osc_mod

    ref = _load_ref()

    # Load a fixed FGONG (the midMS 1.0 M_sun profile)
    fgong_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data", "mesa_comparison", "profiles", "1.0Msun", "midMS.FGONG.gz"
    )
    if not os.path.isfile(fgong_path):
        pytest.skip(f"FGONG reference not found: {fgong_path}")

    # Decompress and read
    import tempfile
    with gzip.open(fgong_path, 'rt') as gz:
        content = gz.read()
    with tempfile.NamedTemporaryFile(mode='w', suffix='.FGONG', delete=False) as tmp:
        tmp.write(content)
        tmp_path = tmp.name

    try:
        glob, var = oscillations.read_fgong(tmp_path)
    finally:
        os.unlink(tmp_path)

    # Compute l=0 eigenfrequency in the solar-like range
    result = osc_mod.compute_eigenfreq_differentiable(
        glob, var, l=0, nu_min=2500.0, nu_max=3500.0
    )

    sigma2 = float(result['sigma2'])

    np.testing.assert_allclose(
        sigma2, float(ref['eigenfreq_sigma2']), atol=0, rtol=1e-9,
        err_msg="eigenfreq σ²(l=0) changed — refactor broke oscillation solver"
    )


# ===========================================================================
# §3. FORWARD EVOLUTION PIN (smoke — needs JIT compile)
# ===========================================================================
# Pin the evolve_star output at fixed_dt. This is the definitive
# characterization test for the full forward pass.
# ===========================================================================


@pytest.mark.suspended  # heavy (JIT compile ~10-16 min) — on-demand/nightly, not per-wave
@pytest.mark.smoke
def test_golden_evolve_star_forward():
    """Pin evolve_star forward output at fixed configuration.

    Quantities pinned:
      - log_L[-1], log_Teff[-1], log_Tc[-1], log_rhoc[-1] (final step scalars)
      - X_profile (final composition, N_COMP=200)
      - y_henyey_final (final Henyey state, (N_HENYEY, 4))

    Config: M=1.0, Z=0.014, max_steps=200, fixed_dt=2e6 yr.
    Tolerance: atol=1e-8, rtol=1e-5 (XLA float-reorder tolerant; see module docstring;
    tiny margin for JAX/XLA minor version differences).
    """
    import stellar_jax.evolution as evolution

    ref = _load_ref()

    result = evolution.evolve_star(
        1.0, Z=0.014, max_steps=200, fixed_dt=2e6,
        diffusion=True, adaptive_mesh=False
    )

    # Final step scalars
    np.testing.assert_allclose(
        float(result['log_L'][-1]), float(ref['evolve_logL_final']),
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_star log_L[-1] changed"
    )
    np.testing.assert_allclose(
        float(result['log_Teff'][-1]), float(ref['evolve_logTe_final']),
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_star log_Teff[-1] changed"
    )
    np.testing.assert_allclose(
        float(result['log_Tc'][-1]), float(ref['evolve_logTc_final']),
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_star log_Tc[-1] changed"
    )
    np.testing.assert_allclose(
        float(result['log_rhoc'][-1]), float(ref['evolve_logrhoc_final']),
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_star log_rhoc[-1] changed"
    )

    # Composition profile (full array)
    np.testing.assert_allclose(
        np.array(result['X_profile']), ref['evolve_X_profile'],
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_star X_profile changed"
    )

    # Henyey state (full array)
    np.testing.assert_allclose(
        np.array(result['y_henyey_final']), ref['evolve_y_henyey_final'],
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_star y_henyey_final changed"
    )


# ===========================================================================
# §4. GRADIENT PINS (integration — backward pass compile)
# ===========================================================================
# Pin AD gradient values. These are the most sensitive characterization tests:
# any change to stop_gradient placement, IFT contracts, or carry structure
# will change these.
# ===========================================================================


@pytest.mark.suspended  # heavy backward-pass compile — on-demand/nightly, not per-wave
@pytest.mark.integration
def test_golden_gradient_dlogL_dM():
    """Pin ∂log_L[-1]/∂M via AD at fixed_dt.

    Quantity pinned: the AD gradient of log_L at the final step w.r.t. mass.
    Config: M=1.0, Z=0.014, max_steps=200, fixed_dt=2e6 yr.
    Tolerance: atol=1e-8, rtol=1e-5 (IFT backward-pass float reorder; see module docstring).
    """
    import stellar_jax.evolution as evolution

    ref = _load_ref()

    if 'grad_dlogL_dM' not in ref:
        pytest.skip(
            "Golden-master reference missing 'grad_dlogL_dM'. "
            "Re-run `python scripts/generate_golden_master.py` to add it."
        )

    def logL_final(mass):
        r = evolution.evolve_star(
            mass, Z=0.014, max_steps=200, fixed_dt=2e6,
            diffusion=True, adaptive_mesh=False
        )
        return r['log_L'][-1]

    grad_val = float(jax.grad(logL_final)(jnp.float64(1.0)))

    np.testing.assert_allclose(
        grad_val, float(ref['grad_dlogL_dM']),
        atol=1e-8, rtol=1e-5,
        err_msg="AD gradient ∂logL/∂M changed — check stop_gradient / IFT"
    )


@pytest.mark.suspended  # heavy backward-pass compile — on-demand/nightly, not per-wave
@pytest.mark.integration
def test_golden_gradient_dlogTe_dalpha():
    """Pin ∂log_Teff[-1]/∂α_MLT via AD at fixed_dt.

    Quantity pinned: the AD gradient of log_Teff at the final step w.r.t. α_MLT.
    Config: M=1.0, Z=0.014, α=1.9, max_steps=200, fixed_dt=2e6 yr.
    Tolerance: atol=1e-8, rtol=1e-5.
    """
    import stellar_jax.evolution as evolution

    ref = _load_ref()

    if 'grad_dlogTe_dalpha' not in ref:
        pytest.skip(
            "Golden-master reference missing 'grad_dlogTe_dalpha'. "
            "Re-run `python scripts/generate_golden_master.py` to add it."
        )

    def logTe_final(alpha):
        r = evolution.evolve_star(
            1.0, Z=0.014, max_steps=200, fixed_dt=2e6, alpha_mlt=alpha,
            diffusion=True, adaptive_mesh=False
        )
        return r['log_Teff'][-1]

    grad_val = float(jax.grad(logTe_final)(jnp.float64(1.9)))

    np.testing.assert_allclose(
        grad_val, float(ref['grad_dlogTe_dalpha']),
        atol=1e-8, rtol=1e-5,
        err_msg="AD gradient ∂logTe/∂α changed — check stop_gradient / IFT"
    )


# ===========================================================================
# §5. SEISMIC GRADIENT PIN (integration — full E2E backward pass)
# ===========================================================================
# Pin ∂σ²/∂M through the complete differentiable chain:
#   mass → evolve_star → structure_to_fgong_jax → build_oscillation_coeffs_jax
#   → eigenfreq_from_coeffs (IFT @custom_vjp)
# This is the most comprehensive refactor guard: it exercises the full forward
# pass, the FGONG builder, the oscillation coefficient extraction, AND the
# IFT-based eigenfrequency adjoint — all in one gradient computation.
# ===========================================================================


@pytest.mark.suspended  # heavy E2E backward-pass compile — on-demand/nightly, not per-wave
@pytest.mark.integration
def test_golden_gradient_dsigma2_dM():
    """Pin ∂σ²(l=0)/∂M through the full evolve→FGONG→eigenfreq chain.

    Quantity pinned: AD gradient of σ²(l=0) w.r.t. stellar mass, computed
    through the entire differentiable chain (evolution + structure + oscillation).
    Config: M=1.0, Z=0.014, max_steps=50, fixed_dt=2e6 yr, diffusion=False.
    Tolerance: atol=1e-8, rtol=1e-5 (the full E2E chain has more floating-point sensitivity
    than isolated gradient tests due to the nested IFT + lax.scan backward pass).

    This test uses fewer steps (max_steps=50) than the forward/gradient pins
    (max_steps=200) to reduce memory and compile time while still exercising
    the complete backward path. The seismic gradient is meaningful even at
    short evolution because the structure changes immediately upon M perturbation.
    """
    import stellar_jax.evolution as evolution
    from stellar_jax.evolution import structure_to_fgong_jax
    from stellar_jax.oscillations import (
        build_oscillation_coeffs_jax, compute_eigenfreq_from_structure_jax,
        eigenfreq_from_coeffs
    )

    ref = _load_ref()

    if 'grad_dsigma2_dM' not in ref:
        pytest.skip(
            "Golden-master reference missing 'grad_dsigma2_dM'. "
            "Re-run `python scripts/generate_golden_master.py` to add it."
        )

    M = 1.0
    Z = 0.014
    alpha = 1.9
    N_steps = 50
    dt_fixed = 2e6
    nu_min, nu_max = 2500.0, 3500.0

    # Step 1: Forward-only run to find the reference eigenfrequency bracket
    # (Brent root-finding is not differentiable — done once outside the AD graph)
    import warnings
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        r_ref = evolution.evolve_star(
            jnp.float64(M), Z=Z, max_steps=N_steps, fixed_dt=dt_fixed,
            alpha_mlt=alpha, diffusion=False, adaptive_mesh=False
        )

    glob_ref, var_ref = structure_to_fgong_jax(
        jnp.float64(M), r_ref['log_L_final'], r_ref['log_Teff_final'],
        r_ref['X_profile'], jnp.float64(Z), jnp.float64(0.0),
        jnp.float64(alpha), y_henyey=r_ref['y_henyey_final'],
        atm_ratio=r_ref.get('atm_ratio'),
    )
    info = compute_eigenfreq_from_structure_jax(
        glob_ref, var_ref, l=0, nu_min=nu_min, nu_max=nu_max,
        n_scan=100, n_steps=8000, mode_index=0
    )
    sigma2_ref = info['sigma2']

    # Step 2: Define the differentiable E2E function
    def sigma2_of_mass(mass_val):
        r = evolution.evolve_star(
            mass_val, Z=Z, max_steps=N_steps, fixed_dt=dt_fixed,
            alpha_mlt=alpha, diffusion=False, adaptive_mesh=False
        )
        glob, var = structure_to_fgong_jax(
            mass_val, r['log_L_final'], r['log_Teff_final'],
            r['X_profile'], jnp.float64(Z), jnp.float64(0.0),
            jnp.float64(alpha), y_henyey=r['y_henyey_final'],
            atm_ratio=r.get('atm_ratio'),
        )
        grid_data = build_oscillation_coeffs_jax(glob, var)
        return eigenfreq_from_coeffs(
            grid_data['coeffs'], grid_data['x_grid'], sigma2_ref,
            info['l'], info['x_steps'], info['h_steps'], info['factor']
        )

    # Step 3: Compute AD gradient
    grad_val = float(jax.grad(sigma2_of_mass)(jnp.float64(M)))

    np.testing.assert_allclose(
        grad_val, float(ref['grad_dsigma2_dM']),
        atol=1e-8, rtol=1e-5,
        err_msg="AD gradient ∂σ²/∂M changed — check IFT/stop_gradient/FGONG builder"
    )


# ===========================================================================
# §6. mlt_nabla VALUE + GRADIENT PIN (fast — pure physics function)
# ===========================================================================
# Pin mlt_nabla output + ∂nabla/∂alpha_mlt on fixed solar-CZ inputs.
# This is the convective transport boundary — a refactor that changes the
# _mlt_switch sigmoid or cubic solve will break this.
# ===========================================================================


@pytest.mark.fast
def test_golden_mlt_nabla_value():
    """Pin mlt_nabla scalar output on fixed convective-zone inputs.

    WHAT: nabla (actual temperature gradient) from MLT for a single
    convective point in the solar CZ.
    WHY: guards the _mlt_cubic_solve + _mlt_switch (custom_jvp) path.
    REFERENCE: self-pinned golden (refactor guard, not physics validation).
    TOLERANCE: atol=0, rtol=0 — pure function, deterministic.
    """
    from stellar_jax.transport.mlt import mlt_nabla
    from stellar_jax.config.constants import G, Msun, Rsun

    ref = _load_ref()

    if 'mlt_nabla_value' not in ref:
        pytest.skip("Golden-master reference missing 'mlt_nabla_value'. "
                     "Re-run generate_golden_master.py.")

    # Fixed solar CZ inputs (same as generation script)
    nabla_rad = jnp.float64(0.6)
    nad = jnp.float64(0.4)
    T = jnp.float64(1e6)
    P = jnp.float64(1e16)
    rho = jnp.float64(0.5)
    kappa = jnp.float64(1.0)
    g = jnp.float64(G * Msun / Rsun**2)
    mu = jnp.float64(0.62)
    alpha_mlt = jnp.float64(1.9)

    nabla_val = float(mlt_nabla(nabla_rad, nad, T, P, rho, kappa, g, mu, alpha_mlt))

    np.testing.assert_allclose(
        nabla_val, float(ref['mlt_nabla_value']), atol=0, rtol=0,
        err_msg="mlt_nabla value changed — refactor broke MLT cubic/switch"
    )


@pytest.mark.fast
def test_golden_mlt_nabla_grad():
    """Pin ∂nabla/∂alpha_mlt from mlt_nabla on fixed inputs.

    WHAT: AD gradient of mlt_nabla w.r.t. alpha_mlt — tests the custom_jvp
    sigmoid blend in _mlt_switch.
    WHY: a refactor that changes nondiff_argnums or the JVP definition will
    break this. Also catches if alpha_mlt accidentally becomes static.
    REFERENCE: self-pinned golden.
    TOLERANCE: atol=0, rtol=0 — pure function with custom_jvp, deterministic.
    """
    from stellar_jax.transport.mlt import mlt_nabla
    from stellar_jax.config.constants import G, Msun, Rsun

    ref = _load_ref()

    if 'mlt_nabla_grad_dalpha' not in ref:
        pytest.skip("Golden-master reference missing 'mlt_nabla_grad_dalpha'. "
                     "Re-run generate_golden_master.py.")

    nabla_rad = jnp.float64(0.6)
    nad = jnp.float64(0.4)
    T = jnp.float64(1e6)
    P = jnp.float64(1e16)
    rho = jnp.float64(0.5)
    kappa = jnp.float64(1.0)
    g = jnp.float64(G * Msun / Rsun**2)
    mu = jnp.float64(0.62)
    alpha_mlt = jnp.float64(1.9)

    grad_fn = jax.grad(lambda a: mlt_nabla(nabla_rad, nad, T, P, rho, kappa,
                                            g, mu, a), argnums=0)
    grad_val = float(grad_fn(alpha_mlt))

    np.testing.assert_allclose(
        grad_val, float(ref['mlt_nabla_grad_dalpha']), atol=0, rtol=0,
        err_msg="mlt_nabla ∂nabla/∂α changed — custom_jvp or cubic solve broke"
    )


# ===========================================================================
# §7. _cell_residual PIN (fast — no evolve_star)
# ===========================================================================


@pytest.mark.fast
def test_golden_cell_residual():
    """Pin _cell_residual 4-vector on fixed solar-interior cell inputs.

    WHAT: the [F1,F2,F3,F4] structure-equation residuals for one Henyey cell.
    WHY: guards the mass/hydrostatic/luminosity/temperature-gradient equations.
    A refactor that changes EOS lookups, opacity, or nuclear rates inside the
    residual will break this.
    REFERENCE: self-pinned golden.
    TOLERANCE: atol=0, rtol=0 — pure function, deterministic.
    """
    from stellar_jax.solver.residual import _cell_residual
    from stellar_jax.config.constants import Msun, Rsun, Lsun

    ref = _load_ref()

    if 'cell_residual_F' not in ref:
        pytest.skip("Golden-master reference missing 'cell_residual_F'. "
                     "Re-run generate_golden_master.py.")

    # Fixed inputs (same as generation script)
    r_inner = 0.3 * Rsun
    r_outer = 0.35 * Rsun
    P_inner = 10**(16.5)
    P_outer = 10**(16.3)
    T_inner = 10**(7.0)
    T_outer = 10**(6.95)
    ell_inner = 0.8
    ell_outer = 0.85

    y_k = jnp.array([np.log(r_inner), np.log(P_inner), np.log(T_inner), ell_inner])
    y_kp1 = jnp.array([np.log(r_outer), np.log(P_outer), np.log(T_outer), ell_outer])
    dm = jnp.float64(0.05 * Msun)
    m_mid = jnp.float64(0.325 * Msun)
    M_star = jnp.float64(1.0 * Msun)
    X_mid = jnp.float64(0.70)
    Z = jnp.float64(0.014)
    alpha_mlt = jnp.float64(1.9)

    F = _cell_residual(y_k, y_kp1, dm, m_mid, M_star, X_mid, Z, alpha_mlt)

    np.testing.assert_allclose(
        np.array(F), ref['cell_residual_F'], atol=0, rtol=0,
        err_msg="_cell_residual output changed — structure equations broke"
    )


# ===========================================================================
# §8. AD-vs-FD CROSS-CHECK for mlt_nabla (fast, independent oracle)
# ===========================================================================
# An AD-vs-FD check_grads provides an INDEPENDENT oracle — the golden only
# proves "same as before", but check_grads proves "AD = truth".
# ===========================================================================


@pytest.mark.fast
def test_mlt_nabla_ad_vs_fd():
    """AD-vs-FD cross-check for mlt_nabla w.r.t. alpha_mlt.

    WHAT: verifies that the custom_jvp gradient in _mlt_switch matches
    a central finite-difference at the same operating point.
    WHY: an independent oracle — if the custom_jvp sigmoid drifts or the
    cubic solve changes, the AD and FD will disagree.
    REFERENCE: finite-difference (central, eps=1e-4) — independent.
    TOLERANCE: rtol=1e-3 (first-order central FD at eps=1e-4 gives O(eps²)=1e-8
    truncation error; the comparison is limited by the FD accuracy).
    """
    from stellar_jax.transport.mlt import mlt_nabla
    from stellar_jax.config.constants import G, Msun, Rsun

    nabla_rad = jnp.float64(0.6)
    nad = jnp.float64(0.4)
    T = jnp.float64(1e6)
    P = jnp.float64(1e16)
    rho = jnp.float64(0.5)
    kappa = jnp.float64(1.0)
    g = jnp.float64(G * Msun / Rsun**2)
    mu = jnp.float64(0.62)
    alpha_mlt = jnp.float64(1.9)

    def nabla_of_alpha(a):
        return mlt_nabla(nabla_rad, nad, T, P, rho, kappa, g, mu, a)

    # AD gradient
    grad_ad = float(jax.grad(nabla_of_alpha)(alpha_mlt))

    # Central finite-difference
    eps = 1e-4
    f_plus = float(nabla_of_alpha(alpha_mlt + eps))
    f_minus = float(nabla_of_alpha(alpha_mlt - eps))
    grad_fd = (f_plus - f_minus) / (2 * eps)

    # The gradient is tiny (~1e-10) at this operating point (barely convective,
    # right at the Schwarzschild boundary). Use absolute tolerance for small values.
    np.testing.assert_allclose(
        grad_ad, grad_fd, atol=1e-12, rtol=1e-3,
        err_msg="mlt_nabla AD gradient disagrees with central FD"
    )


# ===========================================================================
# §9. eigenfreq_radial VJP PRIMAL + COTANGENT PIN (integration)
# ===========================================================================


@pytest.mark.suspended  # heavy custom_vjp backward compile — on-demand/nightly, not per-wave
@pytest.mark.integration
def test_golden_eigenfreq_radial_vjp():
    """Pin eigenfreq_radial primal and ALL cotangents via jax.vjp.

    WHAT: primal σ² and cotangents (g_coeffs, g_x_grid, g_sigma2_in) from
    the IFT @custom_vjp backward pass, pulled with cotangent g_σ²=1.0.
    WHY: the most sensitive adjoint boundary — the x_grid cotangent carries
    ~75% of ∂ν/∂M (OSC-3, issue #373). A refactor that changes nondiff_argnums,
    the determinant function, or the IFT formula will break this.
    REFERENCE: self-pinned golden (cotangent values).
    TOLERANCE: rtol=1e-9 for primal (through XLA compile);
    atol=1e-8, rtol=1e-5 for cotangents (backward pass float reorder).
    """
    from stellar_jax.oscillations import (
        build_oscillation_coeffs_jax, compute_eigenfreq_from_structure_jax,
    )
    from stellar_jax.oscillations.adjoint import eigenfreq_radial
    import stellar_jax.oscillations as oscillations

    ref = _load_ref()

    for key in ('eigenfreq_radial_primal', 'eigenfreq_radial_g_coeffs',
                'eigenfreq_radial_g_x_grid', 'eigenfreq_radial_g_sigma2_in'):
        if key not in ref:
            pytest.skip(f"Golden-master reference missing '{key}'. "
                        "Re-run generate_golden_master.py.")

    # Load fixed FGONG (same as generation script)
    fgong_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data", "mesa_comparison", "profiles", "1.0Msun", "midMS.FGONG.gz"
    )
    if not os.path.isfile(fgong_path):
        pytest.skip(f"FGONG not found: {fgong_path}")

    import tempfile
    with gzip.open(fgong_path, 'rt') as gz:
        content = gz.read()
    with tempfile.NamedTemporaryFile(mode='w', suffix='.FGONG', delete=False) as tmp:
        tmp.write(content)
        tmp_path = tmp.name
    try:
        glob, var = oscillations.read_fgong(tmp_path)
    finally:
        os.unlink(tmp_path)

    info = compute_eigenfreq_from_structure_jax(
        glob, var, l=0, nu_min=2500.0, nu_max=3500.0,
        n_scan=100, n_steps=8000, mode_index=0
    )
    grid_data = build_oscillation_coeffs_jax(glob, var)
    coeffs = grid_data['coeffs']
    x_grid = grid_data['x_grid']
    sigma2_converged = info['sigma2']
    x_steps = info['x_steps']
    h_steps = info['h_steps']
    factor = info['factor']

    primals, vjp_fn = jax.vjp(
        lambda c, xg, s2: eigenfreq_radial(c, xg, s2, x_steps, h_steps, factor),
        coeffs, x_grid, sigma2_converged
    )
    g_coeffs, g_x_grid, g_sigma2_in = vjp_fn(jnp.float64(1.0))

    # Primal
    np.testing.assert_allclose(
        float(primals), float(ref['eigenfreq_radial_primal']), atol=0, rtol=1e-9,
        err_msg="eigenfreq_radial primal σ² changed"
    )
    # Cotangents
    np.testing.assert_allclose(
        np.array(g_coeffs), ref['eigenfreq_radial_g_coeffs'],
        atol=1e-8, rtol=1e-5,
        err_msg="eigenfreq_radial g_coeffs changed — IFT adjoint broke"
    )
    np.testing.assert_allclose(
        np.array(g_x_grid), ref['eigenfreq_radial_g_x_grid'],
        atol=1e-8, rtol=1e-5,
        err_msg="eigenfreq_radial g_x_grid changed — x_grid gradient path broke"
    )
    np.testing.assert_allclose(
        float(g_sigma2_in), float(ref['eigenfreq_radial_g_sigma2_in']),
        atol=1e-8, rtol=1e-5,
        err_msg="eigenfreq_radial g_sigma2_in changed"
    )


# ===========================================================================
# §10. AD-vs-FD for eigenfreq_radial (integration, independent oracle)
# ===========================================================================
# For a custom_vjp function, AD-vs-FD is especially important — it verifies
# the hand-written IFT backward pass against numerical differentiation.
# ===========================================================================


@pytest.mark.suspended  # heavy custom_vjp backward compile — on-demand/nightly, not per-wave
@pytest.mark.integration
def test_eigenfreq_radial_ad_vs_fd():
    """AD-vs-FD cross-check for eigenfreq_radial's IFT adjoint.

    WHAT: verifies that the IFT backward pass (∂σ²/∂coeffs, ∂σ²/∂x_grid)
    matches a central finite-difference through the determinant.
    WHY: independent oracle for the custom_vjp — catches IFT formula errors,
    wrong sign, missing scale factor.
    REFERENCE: finite-difference (central, eps=1e-4).

    NOTE: eigenfreq_radial's forward is identity (returns sigma2_converged),
    so FD of eigenfreq_radial itself would give 0. Instead we FD through the
    determinant D(σ², coeffs) and verify the IFT cotangent direction by
    checking AD(eigenfreq_radial) vs FD-via-determinant on a single coefficient.
    """
    from stellar_jax.oscillations import (
        build_oscillation_coeffs_jax, compute_eigenfreq_from_structure_jax,
    )
    from stellar_jax.oscillations.adjoint import eigenfreq_radial
    from stellar_jax.oscillations.determinant import _radial_det_for_grad
    import stellar_jax.oscillations as oscillations

    # Load fixed FGONG
    fgong_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data", "mesa_comparison", "profiles", "1.0Msun", "midMS.FGONG.gz"
    )
    if not os.path.isfile(fgong_path):
        pytest.skip(f"FGONG not found: {fgong_path}")

    import tempfile
    with gzip.open(fgong_path, 'rt') as gz:
        content = gz.read()
    with tempfile.NamedTemporaryFile(mode='w', suffix='.FGONG', delete=False) as tmp:
        tmp.write(content)
        tmp_path = tmp.name
    try:
        glob, var = oscillations.read_fgong(tmp_path)
    finally:
        os.unlink(tmp_path)

    info = compute_eigenfreq_from_structure_jax(
        glob, var, l=0, nu_min=2500.0, nu_max=3500.0,
        n_scan=100, n_steps=8000, mode_index=0
    )
    grid_data = build_oscillation_coeffs_jax(glob, var)
    coeffs = grid_data['coeffs']
    x_grid = grid_data['x_grid']
    sigma2_converged = info['sigma2']
    x_steps = info['x_steps']
    h_steps = info['h_steps']
    factor = info['factor']

    # AD: get ∂σ²/∂coeffs via the custom_vjp
    _, vjp_fn = jax.vjp(
        lambda c, xg, s2: eigenfreq_radial(c, xg, s2, x_steps, h_steps, factor),
        coeffs, x_grid, sigma2_converged
    )
    g_coeffs_ad, g_x_grid_ad, _ = vjp_fn(jnp.float64(1.0))

    # FD: perturb one coefficient element and re-solve for σ² via IFT formula
    # IFT: ∂σ²/∂c_ij = −(∂D/∂c_ij) / (∂D/∂σ²)
    dD_dsigma2 = jax.grad(_radial_det_for_grad, argnums=0)(
        sigma2_converged, coeffs, x_grid, x_steps, h_steps)

    # Pick a single coefficient to FD-check: coeffs[0, N//2] (Vg at midpoint)
    i, j = 0, coeffs.shape[1] // 2
    eps = 1e-5
    coeffs_plus = coeffs.at[i, j].set(coeffs[i, j] + eps)
    coeffs_minus = coeffs.at[i, j].set(coeffs[i, j] - eps)
    D_plus = _radial_det_for_grad(sigma2_converged, coeffs_plus, x_grid, x_steps, h_steps)
    D_minus = _radial_det_for_grad(sigma2_converged, coeffs_minus, x_grid, x_steps, h_steps)
    dD_dc_fd = (D_plus - D_minus) / (2 * eps)
    dsigma2_dc_fd = -dD_dc_fd / dD_dsigma2

    # Compare AD cotangent at (i,j) to FD
    dsigma2_dc_ad = float(g_coeffs_ad[i, j])
    np.testing.assert_allclose(
        dsigma2_dc_ad, float(dsigma2_dc_fd), rtol=1e-3,
        err_msg=f"eigenfreq_radial IFT adjoint disagrees with FD at coeffs[{i},{j}]"
    )


# ===========================================================================
# §11. _henyey_newton VJP PRIMAL + COTANGENT PIN (integration)
# ===========================================================================


@pytest.mark.suspended  # heavy custom_vjp backward compile — on-demand/nightly, not per-wave
@pytest.mark.integration
def test_golden_henyey_newton_vjp():
    """Pin _henyey_newton primal and ALL cotangents via jax.vjp.

    WHAT: converged Henyey state y_final and cotangents (g_y_init, g_q_mesh,
    g_M_star, g_X_profile, g_Z, g_alpha) from the IFT backward pass.
    WHY: guards the block-Thomas solve + IFT adjoint. A refactor that changes
    the Jacobian blocks, damping, or backward-pass VJP will break this.
    REFERENCE: self-pinned golden.
    TOLERANCE: atol=1e-8, rtol=1e-5 for primal + cotangents (Newton iteration
    + IFT backward through XLA compile).
    """
    from stellar_jax.solver.newton import _henyey_newton
    from stellar_jax.structure import initial_guess, newton_solve_xprofile, build_model_on_mesh
    from stellar_jax.config.constants import Msun, Lsun, Y_BBN, DY_DZ
    from stellar_jax.config.mesh_defaults import N_COMP, N_NEWTON_COLD

    ref = _load_ref()

    for key in ('henyey_newton_y_final', 'henyey_newton_g_y_init',
                'henyey_newton_g_M_star', 'henyey_newton_g_alpha'):
        if key not in ref:
            pytest.skip(f"Golden-master reference missing '{key}'. "
                        "Re-run generate_golden_master.py.")

    M_solar = 1.0
    Z = 0.014
    alpha_mlt = 1.9
    n_iter = 15

    Y = Y_BBN + DY_DZ * Z
    X_init = 1.0 - Y - Z
    X_profile = jnp.full(N_COMP, X_init)

    logL_g, logTe_g = initial_guess(jnp.float64(M_solar))
    logL, logTe = newton_solve_xprofile(
        jnp.float64(M_solar), X_profile, jnp.float64(Z), jnp.float64(0.0),
        jnp.float64(logL_g), jnp.float64(logTe_g), jnp.float64(alpha_mlt),
        N_NEWTON_COLD)
    model = build_model_on_mesh(jnp.float64(M_solar), logL, logTe, X_profile,
                                jnp.float64(Z), jnp.float64(alpha_mlt), 200)
    q_mesh = model['q']
    M_star = jnp.float64(M_solar * Msun)
    ln_r = jnp.log(jnp.maximum(model['r'], 1.0))
    ln_P = jnp.log(10.0) * model['logP']
    ln_T = jnp.log(10.0) * model['logT']
    ell = model['L'] / Lsun
    y_full = jnp.stack([ln_r, ln_P, ln_T, ell], axis=-1)
    N_s = q_mesh.shape[0] - 1
    y_init = y_full[:N_s]

    primals, vjp_fn = jax.vjp(
        lambda yi, qm, ms, xp, z, a: _henyey_newton(yi, qm, ms, xp, z, a, n_iter),
        y_init, q_mesh, M_star, X_profile, jnp.float64(Z), jnp.float64(alpha_mlt)
    )
    g_out = jnp.ones_like(primals)
    g_y_init, g_q_mesh, g_M_star, g_X_profile, g_Z, g_alpha = vjp_fn(g_out)

    # Primal
    np.testing.assert_allclose(
        np.array(primals), ref['henyey_newton_y_final'],
        atol=1e-8, rtol=1e-5,
        err_msg="_henyey_newton y_final changed — Newton solver broke"
    )
    # Cotangents
    np.testing.assert_allclose(
        np.array(g_y_init), ref['henyey_newton_g_y_init'],
        atol=1e-8, rtol=1e-5,
        err_msg="_henyey_newton g_y_init changed — IFT backward broke"
    )
    np.testing.assert_allclose(
        np.array(g_q_mesh), ref['henyey_newton_g_q_mesh'],
        atol=1e-8, rtol=1e-5,
        err_msg="_henyey_newton g_q_mesh changed"
    )
    np.testing.assert_allclose(
        float(g_M_star), float(ref['henyey_newton_g_M_star']),
        atol=1e-8, rtol=1e-5,
        err_msg="_henyey_newton g_M_star changed"
    )
    np.testing.assert_allclose(
        np.array(g_X_profile), ref['henyey_newton_g_X_profile'],
        atol=1e-8, rtol=1e-5,
        err_msg="_henyey_newton g_X_profile changed"
    )
    np.testing.assert_allclose(
        float(g_Z), float(ref['henyey_newton_g_Z']),
        atol=1e-8, rtol=1e-5,
        err_msg="_henyey_newton g_Z changed"
    )
    np.testing.assert_allclose(
        float(g_alpha), float(ref['henyey_newton_g_alpha']),
        atol=1e-8, rtol=1e-5,
        err_msg="_henyey_newton g_alpha changed"
    )


# ===========================================================================
# §12. evolve_star ONE-STEP FORWARD + GRADIENT PIN (integration)
# ===========================================================================


@pytest.mark.suspended  # heavy (ZAMS + one scan-body compile) — on-demand/nightly, not per-wave
@pytest.mark.integration
def test_golden_evolve_one_step_forward():
    """Pin evolve_star(max_steps=1) forward output.

    WHAT: log_L[0] and log_Teff[0] from a single evolution step.
    WHY: guards the ZAMS initialization + one scan-body iteration.
    REFERENCE: self-pinned golden.
    TOLERANCE: atol=1e-8, rtol=1e-5 (XLA compile float reorder).
    """
    import stellar_jax.evolution as evolution

    ref = _load_ref()

    if 'evolve_1step_logL' not in ref:
        pytest.skip("Golden-master reference missing 'evolve_1step_logL'. "
                     "Re-run generate_golden_master.py.")

    r = evolution.evolve_star(
        1.0, Z=0.014, max_steps=1, fixed_dt=2e6,
        diffusion=True, adaptive_mesh=False
    )

    np.testing.assert_allclose(
        float(r['log_L'][0]), float(ref['evolve_1step_logL']),
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_star(max_steps=1) log_L changed"
    )
    np.testing.assert_allclose(
        float(r['log_Teff'][0]), float(ref['evolve_1step_logTe']),
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_star(max_steps=1) log_Teff changed"
    )


@pytest.mark.suspended  # heavy (backward through one scan iter + ZAMS IFT) — on-demand/nightly
@pytest.mark.integration
def test_golden_evolve_one_step_gradient():
    """Pin ∂logL[0]/∂M from evolve_star(max_steps=1).

    WHAT: AD gradient of the first-step log_L w.r.t. mass.
    WHY: guards the backward pass through one scan iteration + ZAMS IFT.
    REFERENCE: self-pinned golden.
    TOLERANCE: atol=1e-8, rtol=1e-5.
    """
    import stellar_jax.evolution as evolution

    ref = _load_ref()

    if 'evolve_1step_grad_dlogL_dM' not in ref:
        pytest.skip("Golden-master reference missing 'evolve_1step_grad_dlogL_dM'. "
                     "Re-run generate_golden_master.py.")

    def logL_one_step(mass):
        r = evolution.evolve_star(
            mass, Z=0.014, max_steps=1, fixed_dt=2e6,
            diffusion=True, adaptive_mesh=False
        )
        return r['log_L'][0]

    grad_val = float(jax.grad(logL_one_step)(jnp.float64(1.0)))

    np.testing.assert_allclose(
        grad_val, float(ref['evolve_1step_grad_dlogL_dM']),
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_star(max_steps=1) gradient ∂logL/∂M changed"
    )


# ===========================================================================
# §13. evolve_solar FORWARD + GRADIENT PIN (integration)
# ===========================================================================


@pytest.mark.suspended  # heavy (shooting-solver scan compile) — on-demand/nightly, not per-wave
@pytest.mark.integration
def test_golden_evolve_solar_forward():
    """Pin evolve_solar(max_steps=5) forward output.

    WHAT: log_L[-1] and log_Te[-1] from a short solar evolution.
    WHY: guards the shooting-solver-based evolution path (separate from
    evolve_star's Henyey continuation).
    REFERENCE: self-pinned golden.
    TOLERANCE: atol=1e-8, rtol=1e-5 (XLA compile).
    """
    from stellar_jax.calibration.solar import evolve_solar

    ref = _load_ref()

    if 'evolve_solar_logL_final' not in ref:
        pytest.skip("Golden-master reference missing 'evolve_solar_logL_final'. "
                     "Re-run generate_golden_master.py.")

    ages, log_L, log_R, log_Te, X_final, Y_final, Z_final = evolve_solar(
        jnp.float64(1.9), jnp.float64(0.28), jnp.float64(0.014), max_steps=5
    )

    np.testing.assert_allclose(
        float(log_L[-1]), float(ref['evolve_solar_logL_final']),
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_solar log_L[-1] changed"
    )
    np.testing.assert_allclose(
        float(log_Te[-1]), float(ref['evolve_solar_logTe_final']),
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_solar log_Te[-1] changed"
    )


@pytest.mark.suspended  # OOM at ci-mega (120 GB) — backward pass through shooting-solver scan
@pytest.mark.integration
def test_golden_evolve_solar_gradient():
    """Pin ∂logL[-1]/∂alpha_mlt from evolve_solar(max_steps=5).

    WHAT: AD gradient of the last-step log_L w.r.t. alpha_mlt.
    WHY: guards the backward pass through the shooting-solver evolution path.
    REFERENCE: self-pinned golden.
    TOLERANCE: atol=1e-8, rtol=1e-5.
    SUSPENDED: OOMs at ci-mega (120 GB). The golden value is committed and
    verified locally; the test will be re-enabled when CI memory increases
    or jax.checkpoint is applied to evolve_solar's scan body.
    """
    from stellar_jax.calibration.solar import evolve_solar

    ref = _load_ref()

    if 'evolve_solar_grad_dlogL_dalpha' not in ref:
        pytest.skip("Golden-master reference missing 'evolve_solar_grad_dlogL_dalpha'. "
                     "Re-run generate_golden_master.py.")

    def solar_logL_final(alpha):
        _ages, _logL, _logR, _logTe, _X, _Y, _Z = evolve_solar(
            alpha, jnp.float64(0.28), jnp.float64(0.014), max_steps=5
        )
        return _logL[-1]

    grad_val = float(jax.grad(solar_logL_final)(jnp.float64(1.9)))

    np.testing.assert_allclose(
        grad_val, float(ref['evolve_solar_grad_dlogL_dalpha']),
        atol=1e-8, rtol=1e-5,
        err_msg="evolve_solar gradient ∂logL/∂α changed"
    )


# ===========================================================================
# §14. STRUCTURAL PYTREE ASSERTIONS (fast — no compile)
# ===========================================================================
# These assert that key differentiated parameters are pytree LEAVES (not
# static/nondiff) in the current loose-arg signatures. After bundling
# refactors (B1-B4), these become meaningful structural guards: they catch
# a differentiated array wrongly marked as static (the silent-zero-gradient bug).
# ===========================================================================


@pytest.mark.fast
def test_structural_mlt_nabla_alpha_is_differentiable():
    """Assert alpha_mlt is LIVE in mlt_nabla's gradient (not static/stop_gradient'd).

    A refactor that accidentally makes alpha_mlt a static arg (e.g. bundled into
    a meta_field of a frozen config) or wraps it in stop_gradient would make this
    gradient exactly zero. This test catches that: it evaluates at a genuinely
    SUPERADIABATIC operating point (efficient convection, low density) where alpha
    materially controls the temperature gradient, so ∂nabla/∂alpha is a robust
    ~1e-2 (NOT the ~1e-9 numerical floor you get at a barely-convective point) —
    and asserts it is finite AND meaningfully nonzero.

    NOTE (verified 2026-09-10): at the earlier operating point (T=1e6,P=1e16,
    rho=0.5) mlt_nabla sits on the adiabatic floor (returns nad=0.4) and ∂/∂alpha
    is ~1e-9 — indistinguishable from a static-zero gradient, so a nonzero check
    there was impossible. This point (T=1e5,P=1e8,rho=1e-5,kappa=100,nabla_rad=10)
    gives nabla≈0.411 (above the 0.4 floor) and ∂/∂alpha≈-7.9e-3.
    """
    from stellar_jax.transport.mlt import mlt_nabla
    from stellar_jax.config.constants import G, Msun, Rsun

    # Superadiabatic, low-density point: MLT is efficient, alpha matters.
    nabla_rad = jnp.float64(10.0)
    nad = jnp.float64(0.4)
    T = jnp.float64(1e5)
    P = jnp.float64(1e8)
    rho = jnp.float64(1e-5)
    kappa = jnp.float64(100.0)
    g = jnp.float64(G * Msun / Rsun**2)
    mu = jnp.float64(0.62)

    def nabla_of_alpha(a):
        return mlt_nabla(nabla_rad, nad, T, P, rho, kappa, g, mu, a)

    val = float(nabla_of_alpha(jnp.float64(1.9)))
    grad_val = float(jax.grad(nabla_of_alpha)(jnp.float64(1.9)))

    # Sanity: we're genuinely off the adiabatic floor (else the test is vacuous).
    assert val > float(nad) + 1e-4, (
        f"mlt_nabla is on the adiabatic floor here (nabla={val} ≈ nad={float(nad)}); "
        "the structural test needs a superadiabatic point where alpha matters.")
    assert np.isfinite(grad_val), "mlt_nabla gradient w.r.t. alpha is not finite"
    # The real guard: alpha must be a LIVE input. A static/stop_gradient'd alpha
    # gives exactly 0.0 here (where a live alpha gives ~1e-2).
    assert abs(grad_val) > 1e-6, (
        f"∂nabla/∂alpha = {grad_val:.3e} ≈ 0 at a superadiabatic point where alpha "
        "MUST matter — alpha_mlt was made static / stop_gradient'd by a refactor "
        "(the silent-zero-gradient bug).")


@pytest.mark.fast
def test_structural_cell_residual_differentiable_params():
    """Assert that key physics params flow through _cell_residual's gradient.

    Verifies that y_k, y_kp1, X_mid, Z, and alpha_mlt are all in the
    differentiable path (gradient is finite and not NaN).
    """
    from stellar_jax.solver.residual import _cell_residual
    from stellar_jax.config.constants import Msun, Rsun, Lsun

    r_inner = 0.3 * Rsun
    r_outer = 0.35 * Rsun
    y_k = jnp.array([np.log(r_inner), np.log(10**(16.5)), np.log(10**(7.0)), 0.8])
    y_kp1 = jnp.array([np.log(r_outer), np.log(10**(16.3)), np.log(10**(6.95)), 0.85])
    dm = jnp.float64(0.05 * Msun)
    m_mid = jnp.float64(0.325 * Msun)
    M_star = jnp.float64(1.0 * Msun)
    X_mid = jnp.float64(0.70)
    Z = jnp.float64(0.014)
    alpha_mlt = jnp.float64(1.9)

    # Check gradient w.r.t. y_k (sum of residuals → scalar)
    def residual_sum_yk(yk):
        return jnp.sum(_cell_residual(yk, y_kp1, dm, m_mid, M_star, X_mid, Z, alpha_mlt))

    g_yk = jax.grad(residual_sum_yk)(y_k)
    assert jnp.all(jnp.isfinite(g_yk)), "cell_residual gradient w.r.t. y_k has non-finite elements"

    # Check gradient w.r.t. alpha_mlt
    def residual_sum_alpha(a):
        return jnp.sum(_cell_residual(y_k, y_kp1, dm, m_mid, M_star, X_mid, Z, a))

    g_alpha = jax.grad(residual_sum_alpha)(alpha_mlt)
    assert jnp.isfinite(g_alpha), "cell_residual gradient w.r.t. alpha_mlt is not finite"


@pytest.mark.fast
def test_structural_eigenfreq_radial_nondiff_argnums():
    """Assert eigenfreq_radial's nondiff_argnums match the expected contract.

    After bundling, if someone changes nondiff_argnums (e.g., accidentally
    marks coeffs as static), the custom_vjp breaks silently. This test
    verifies the structural contract.
    """
    from stellar_jax.oscillations.adjoint import eigenfreq_radial

    # eigenfreq_radial is a custom_vjp wrapper — check its nondiff_argnums
    # The underlying function is wrapped by jax.custom_vjp, which stores
    # nondiff_argnums on the wrapper.
    assert hasattr(eigenfreq_radial, 'nondiff_argnums'), \
        "eigenfreq_radial lost its @custom_vjp decoration"
    assert eigenfreq_radial.nondiff_argnums == (3, 4, 5), \
        f"eigenfreq_radial nondiff_argnums changed from (3,4,5) to {eigenfreq_radial.nondiff_argnums}"


@pytest.mark.fast
def test_structural_henyey_newton_nondiff_argnums():
    """Assert _henyey_newton's nondiff_argnums match the expected contract.

    _henyey_newton has nondiff_argnums=(6,) for n_iter. A refactor that
    changes this breaks the IFT backward pass.
    """
    from stellar_jax.solver.newton import _henyey_newton

    assert hasattr(_henyey_newton, 'nondiff_argnums'), \
        "_henyey_newton lost its @custom_vjp decoration"
    assert _henyey_newton.nondiff_argnums == (6,), \
        f"_henyey_newton nondiff_argnums changed from (6,) to {_henyey_newton.nondiff_argnums}"


@pytest.mark.fast
def test_golden_metadata():
    """Verify the golden-master npz contains jax version + git sha metadata."""
    ref = _load_ref()

    assert '_metadata_jax_version' in ref, \
        "Golden-master npz missing _metadata_jax_version"
    assert '_metadata_git_sha' in ref, \
        "Golden-master npz missing _metadata_git_sha"
    # Just verify they're non-empty strings
    jax_ver = str(ref['_metadata_jax_version'])
    git_sha = str(ref['_metadata_git_sha'])
    assert len(jax_ver) > 0, "jax_version metadata is empty"
    assert len(git_sha) > 0, "git_sha metadata is empty"