#!/usr/bin/env python3
"""
Multi-mass HR diagram: stellar-jax forward evolution vs MESA reference tracks.

Produces a Hertzsprung–Russell diagram (log Teff vs log L) showing stellar-jax
forward-evolution tracks overlaid on identical-physics MESA reference tracks for
1.0, 1.5, and 2.0 M☉, from ZAMS through the subgiant branch and up the RGB.
The 1.5 M☉ subgiant operating point where the through-evolution ∂ν²/∂M gradient
is evaluated is marked.

Two modes:

  Default (plot only) — reads committed data, produces the figure in seconds:
    python generate_hr_tracks.py

  Compute — runs evolve_star_adaptive for each mass (hours), saves .npz tracks:
    python generate_hr_tracks.py --compute

The MESA reference tracks are committed at data/mesa_comparison/rgb/<M>Msun/.
The stellar-jax forward tracks are pre-computed .npz files stored in data/ next
to this script, generated by --compute and then committed.

The stellar-jax tracks are plotted as **scatter points** (not connected lines).
The committed tracks use max_steps=500 (practical compute time), and connecting
consecutive steps produces non-physical zigzag artifacts from the adaptive
timestepping.  Scatter points honestly show where the solver placed its accepted
steps; the smooth MESA reference lines (10 000+ model numbers, dashed) provide
context.  The CI-validated runs (max_steps=5000) are smoother; the CI suite
validates each evolutionary phase against the MESA reference (see below).

Physics: MODE-A identical-physics (MESA_CONFIG from inlist_1.0Msun):
  Z=0.014, alpha_mlt=2.0, Y_init=0.2695, diffusion=False, f_ov=0.0.

Validation gate (composite — different CI tests cover different phases):
  MS:  |Δlog L| < 0.10 dex, |Δlog Teff| < 0.03 dex at matched Xc
       (test_mesa_comparison)
  SGB: |Δlog L| < 0.15 dex at matched Xc
       (test_post_tams_core_contraction)
  RGB: median |Δlog Teff| < 0.08 dex on the Hayashi track
       (test_adaptive_forward_rgb_{1p0,1p5,2p0})

Subgiant gradient operating point (1.5 M☉): ∂ν²/∂M evaluated at the early
subgiant (X_c < 0.01, ~50 steps past TAMS). AD vs independent FD: 24.5%,
sign-correct. Hard target <15% (tracked in #1298/#1299).

Output:
  figures/hr_tracks_vs_mesa.png

References:
  MESA: Paxton et al. (2011, 2013, 2015, 2018, 2019) — instrument papers.
  MESA data provenance: data/mesa_comparison/rgb/README.md.
  GRADSOLVE: arXiv:2609.02876, §3.1–3.2 (record–replay gradient construction).
  Christensen-Dalsgaard (2008), Ap&SS 316, 113 (oscillation coefficients).
"""

import argparse
import gzip
import os
import sys

import numpy as np

# ---------------------------------------------------------------------------
# Paths (all relative to this script, following the demo convention)
# ---------------------------------------------------------------------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_FIGURES_DIR = os.path.join(_SCRIPT_DIR, "figures")
_TRACK_DATA_DIR = os.path.join(_SCRIPT_DIR, "data")
_MESA_RGB_DIR = os.path.join(
    _SCRIPT_DIR, "..", "..", "src", "stellar_jax", "data",
    "mesa_comparison", "rgb",
)

# The masses to plot and their display labels.
MASSES = [1.0, 1.5, 2.0]
MASS_LABELS = {1.0: r"1.0 M$_\odot$", 1.5: r"1.5 M$_\odot$", 2.0: r"2.0 M$_\odot$"}

# Colours: distinct, publication-quality palette.
# MESA = lighter/dashed; stellar-jax = solid/darker.
MESA_COLORS = {1.0: "#6baed6", 1.5: "#fdae6b", 2.0: "#a1d99b"}
SJAX_COLORS = {1.0: "#08519c", 1.5: "#e6550d", 2.0: "#31a354"}


# ---------------------------------------------------------------------------
# Matplotlib with Agg backend (following the demo convention — no display)
# ---------------------------------------------------------------------------
def _get_plt():
    """Import matplotlib.pyplot with the non-interactive Agg backend."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    return plt


# ---------------------------------------------------------------------------
# MESA track loader (self-contained, no dependency on tests/mesa_rgb.py)
# ---------------------------------------------------------------------------
def load_mesa_rgb_history(mass):
    """Load a MESA history.data.gz into {column: ndarray}.

    Parses the standard MESA history format: header block, column-name row
    (starts with 'model_number'), then numeric data rows.
    """
    path = os.path.join(_MESA_RGB_DIR, f"{mass}Msun", "history.data.gz")
    if not os.path.exists(path):
        raise FileNotFoundError(f"MESA RGB track not found: {path}")
    with gzip.open(path, "rt") as f:
        lines = f.readlines()
    header = None
    data_start = None
    for i, line in enumerate(lines):
        if line.strip().startswith("model_number"):
            header = line.split()
            data_start = i + 1
            break
    if header is None:
        raise ValueError(f"No 'model_number' header row in {path}")
    data = np.loadtxt(lines[data_start:])
    return {name: data[:, idx] for idx, name in enumerate(header)}


# ---------------------------------------------------------------------------
# stellar-jax track loader (reads pre-computed .npz from --compute)
# ---------------------------------------------------------------------------
def _track_npz_path(mass):
    return os.path.join(_TRACK_DATA_DIR, f"sjax_track_{mass}Msun.npz")


def load_sjax_track(mass):
    """Load a pre-computed stellar-jax forward track (.npz).

    Returns a dict with keys: log_Teff, log_L, star_age, center_h1.
    """
    path = _track_npz_path(mass)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"stellar-jax track not found: {path}\n"
            f"Run  python {os.path.basename(__file__)} --compute  to generate."
        )
    d = dict(np.load(path))
    return d


# ---------------------------------------------------------------------------
# Subgiant operating point locator
# ---------------------------------------------------------------------------
def find_subgiant_point(track, x_c_cutoff=0.01, n_margin=50):
    """Find the subgiant operating point on a track.

    The subgiant point is defined as the point n_margin steps past TAMS
    (where center_h1 drops below x_c_cutoff). This matches the operating
    point used in test_replay_gradient_seismic_subgiant.

    Parameters
    ----------
    track : dict
        Must contain 'center_h1', 'log_Teff', 'log_L'.
    x_c_cutoff : float
        Central hydrogen mass fraction threshold for TAMS.
    n_margin : int
        Number of steps past TAMS to place the operating point.

    Returns
    -------
    log_teff, log_l : float
        Coordinates of the subgiant operating point, or None if not reached.
    """
    xc = track["center_h1"]
    tams_idx = None
    for i, x in enumerate(xc):
        if x < x_c_cutoff:
            tams_idx = i
            break
    if tams_idx is None:
        return None, None
    op_idx = min(tams_idx + n_margin, len(xc) - 1)
    return float(track["log_Teff"][op_idx]), float(track["log_L"][op_idx])


# ---------------------------------------------------------------------------
# Compute mode: run evolve_star_adaptive and save .npz tracks
# ---------------------------------------------------------------------------
def compute_tracks():
    """Run evolve_star_adaptive for each mass and save .npz track files.

    This is SLOW (hours per mass on CPU). Run once; commit the .npz outputs.

    Uses MODE-A identical-physics config (MESA_CONFIG) for a fair comparison.
    max_steps=5000 matches the CI-validated test_adaptive_forward_rgb_* runs,
    producing smooth tracks through the full RGB.  (The committed tracks were
    generated with max_steps=500 as a practical compromise; rerunning with
    --compute produces higher-resolution tracks.)
    """
    # Import stellar_jax (enables float64) and the evolution API.
    import stellar_jax  # noqa: F401 — enables jax_enable_x64
    from stellar_jax.evolution.adaptive import evolve_star_adaptive
    from stellar_jax.config.mesa_config import MESA_CONFIG

    os.makedirs(_TRACK_DATA_DIR, exist_ok=True)

    for mass in MASSES:
        out_path = _track_npz_path(mass)
        print(f"\n{'='*60}")
        print(f"Computing stellar-jax track for {mass} M☉ (MODE-A)...")
        print(f"  Config: {MESA_CONFIG}")
        print(f"  Output: {out_path}")
        print(f"{'='*60}")

        traj, result = evolve_star_adaptive(
            mass=mass,
            N_zones=600,
            max_steps=5000,
            verbose=True,
            **MESA_CONFIG,
        )

        # Extract track arrays from the summary dict.
        log_L = np.asarray(result["log_L"])
        log_Teff = np.asarray(result["log_Teff"])
        star_age = np.asarray(result["star_age"])

        # Extract center_h1 from the trajectory steps (not in summary).
        accepted = [s for s in traj.steps if s.accepted]
        center_h1 = np.array([float(s.X_profile[0]) for s in accepted])

        # Truncate to the same length (summary may have fewer entries if
        # final steps weren't accepted).
        n = min(len(log_L), len(center_h1))
        log_L = log_L[:n]
        log_Teff = log_Teff[:n]
        star_age = star_age[:n]
        center_h1 = center_h1[:n]

        np.savez_compressed(
            out_path,
            log_L=log_L,
            log_Teff=log_Teff,
            star_age=star_age,
            center_h1=center_h1,
            mass=np.float64(mass),
            # Provenance metadata.
            mesa_config_Z=np.float64(MESA_CONFIG["Z"]),
            mesa_config_alpha_mlt=np.float64(MESA_CONFIG["alpha_mlt"]),
            mesa_config_Y_init=np.float64(MESA_CONFIG["Y_init"]),
        )
        print(f"  Saved {n} accepted steps to {out_path}")
        print(f"  logL range: [{log_L.min():.3f}, {log_L.max():.3f}]")
        print(f"  logTeff range: [{log_Teff.min():.4f}, {log_Teff.max():.4f}]")
        print(f"  X_c range: [{center_h1.min():.6f}, {center_h1.max():.6f}]")


# ---------------------------------------------------------------------------
# Plot
# ---------------------------------------------------------------------------
def make_figure():
    """Produce the HR-diagram figure from committed data.

    Reads MESA RGB reference tracks and stellar-jax forward tracks (.npz),
    produces the overlay figure with the subgiant gradient annotation.

    The stellar-jax tracks are plotted as scatter points (not connected lines)
    because the committed tracks use max_steps=500, which is coarse enough
    that connecting consecutive points produces non-physical zigzag artifacts
    from the adaptive timestep.  Scatter points honestly show where the solver
    placed its accepted steps; the MESA tracks (10 000+ model numbers) are
    smooth reference lines.  The CI suite validates each evolutionary phase
    against MESA: |Δlog L| < 0.10 dex on the MS, median |Δlog Teff| < 0.08
    on the RGB (see module docstring for the full composite gate).
    """
    plt = _get_plt()
    os.makedirs(_FIGURES_DIR, exist_ok=True)

    fig, ax = plt.subplots(1, 1, figsize=(8, 6))

    # ── Vertical trim ──
    # Show the well-resolved regime: ZAMS through the subgiant and the
    # lower RGB (log L ≤ 2.0).  Above this, the 500-step tracks have large
    # age gaps and the scatter becomes sparse/misleading.  The MESA reference
    # extends higher (dashed lines visible above the trim) to give context.
    _SJAX_LOGL_CEIL = 2.0

    for mass in MASSES:
        label_mesa = f"MESA {MASS_LABELS[mass]}"
        label_sjax = f"stellar-jax {MASS_LABELS[mass]}"

        # MESA track — smooth reference line (full extent for context).
        mesa = load_mesa_rgb_history(mass)
        ax.plot(
            mesa["log_Teff"], mesa["log_L"],
            color=MESA_COLORS[mass], linewidth=2.0, linestyle="--",
            label=label_mesa, zorder=1, alpha=0.7,
        )

        # stellar-jax track — scatter points, trimmed.
        try:
            sjax = load_sjax_track(mass)
            log_teff = sjax["log_Teff"]
            log_l = sjax["log_L"]
            mask = log_l <= _SJAX_LOGL_CEIL
            ax.scatter(
                log_teff[mask], log_l[mask],
                color=SJAX_COLORS[mass], s=6, alpha=0.7,
                edgecolors="none", zorder=2,
                label=label_sjax,
            )
        except FileNotFoundError:
            print(f"  WARNING: No stellar-jax track for {mass} M☉ — "
                  f"run --compute to generate.")

    # ── Mark the 1.5 M☉ subgiant gradient operating point ──
    sg_teff, sg_logL = None, None
    sg_source = None
    try:
        sjax_1p5 = load_sjax_track(1.5)
        sg_teff, sg_logL = find_subgiant_point(sjax_1p5)
        sg_source = "stellar-jax"
    except FileNotFoundError:
        # Fallback: approximate from MESA data (tracks agree <0.1 dex).
        mesa_1p5 = load_mesa_rgb_history(1.5)
        sg_teff, sg_logL = find_subgiant_point({
            "center_h1": mesa_1p5["center_h1"],
            "log_Teff": mesa_1p5["log_Teff"],
            "log_L": mesa_1p5["log_L"],
        })
        sg_source = "MESA (fallback)"

    if sg_teff is not None and sg_logL is not None:
        ax.plot(
            sg_teff, sg_logL,
            marker="*", markersize=18, color="#e6550d",
            markeredgecolor="black", markeredgewidth=0.8,
            zorder=10,
        )
        ax.annotate(
            r"$\partial\nu^2/\partial M$" + "\n"
            r"(24.5%, sign $\checkmark$)",
            xy=(sg_teff, sg_logL),
            xytext=(sg_teff + 0.06, sg_logL + 0.35),
            fontsize=9,
            ha="left", va="bottom",
            arrowprops=dict(
                arrowstyle="->", color="black",
                connectionstyle="arc3,rad=-0.2",
            ),
            bbox=dict(
                boxstyle="round,pad=0.3", facecolor="white",
                edgecolor="black", alpha=0.9,
            ),
            zorder=11,
        )
        if sg_source != "stellar-jax":
            print(f"  NOTE: subgiant annotation placed from {sg_source} "
                  f"(our track not yet committed — run --compute).")

    # ── Axes ──
    # HR diagram convention: Teff decreasing (hot → cool) left to right.
    ax.invert_xaxis()
    ax.set_xlim(4.05, 3.55)   # log Teff range: hot end through cool SGB
    ax.set_ylim(-0.2, 2.5)    # log L range: ZAMS to lower RGB
    ax.set_xlabel(r"$\log\,T_{\rm eff}$ [K]", fontsize=13)
    ax.set_ylabel(r"$\log\,L/L_\odot$", fontsize=13)
    ax.set_title(
        "Forward evolution: stellar-jax vs MESA (MODE-A identical physics)",
        fontsize=12,
    )
    ax.tick_params(labelsize=11)

    # ── Legend ──
    # Manually reorder so each ROW pairs (MESA, stellar-jax) for the same
    # mass.  matplotlib ncol=2 fills COLUMN-MAJOR, so to get row-major pairs
    # we supply: [all left-column entries, then all right-column entries].
    #   Left column:  MESA 1.0, MESA 1.5, MESA 2.0
    #   Right column: stellar-jax 1.0, stellar-jax 1.5, stellar-jax 2.0
    handles, labels = ax.get_legend_handles_labels()
    label_order = (
        [f"MESA {MASS_LABELS[m]}" for m in MASSES]
        + [f"stellar-jax {MASS_LABELS[m]}" for m in MASSES]
    )
    handle_map = dict(zip(labels, handles))
    ordered_handles = [handle_map[l] for l in label_order if l in handle_map]
    ordered_labels = [l for l in label_order if l in handle_map]
    ax.legend(
        ordered_handles, ordered_labels,
        loc="lower left", fontsize=9, ncol=2,
        framealpha=0.9, edgecolor="gray",
    )

    # ── Caption annotation (bottom-right) ──
    caption = (
        "MODE-A: Z=0.014, α$_{\\rm MLT}$=2.0, Y=0.2695,\n"
        "no diffusion, no overshoot.\n"
        "Points: 500-step adaptive snapshots.\n"
        "CI-validated: |Δlog Teff| < 0.08 (RGB),\n"
        "|Δlog L| < 0.10 (MS), |Δlog L| < 0.15 (SGB).\n"
        "★ ∂ν²/∂M at 1.5 M$_\\odot$ subgiant:\n"
        "    AD vs FD = 24.5%, sign-correct."
    )
    ax.text(
        0.98, 0.02, caption,
        transform=ax.transAxes,
        fontsize=7.5, va="bottom", ha="right",
        bbox=dict(boxstyle="round,pad=0.4", facecolor="#f7f7f7",
                  edgecolor="gray", alpha=0.9),
    )

    fig.tight_layout()
    out_path = os.path.join(_FIGURES_DIR, "hr_tracks_vs_mesa.png")
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="HR diagram: stellar-jax forward evolution vs MESA.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--compute", action="store_true",
        help="Run evolve_star_adaptive for each mass and save .npz tracks "
             "(SLOW — hours per mass). Run once, commit the outputs.",
    )
    parser.add_argument(
        "--no-figure", action="store_true",
        help="Skip figure generation (useful with --compute to only save data).",
    )
    args = parser.parse_args()

    if args.compute:
        compute_tracks()

    if not args.no_figure:
        make_figure()


if __name__ == "__main__":
    main()
